Works on Mac

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8,29 +8,6 @@ function err() {
     exit 1
 }
 
-printf "Looking for c++ compiler... "
-for x in clang++ g++; do
-    if which $x &>/dev/null; then
-        cxx=$x
-        break
-    fi
-done
-if [ -z "$cxx" ]; then
-    err "Cannot locate c++ compiler."
-fi
-printf "OK: ${cxx}\n"
-
-case $(uname) in
-    Darwin)
-        cxxflags="-std=c++11 -g -Wall"
-        ldflags="-lrt -lpthread"
-        ;;        
-    *)
-        cxxflags="-std=c++11 -g -Wall"
-        ldflags="-lrt -lpthread"
-        ;;
-esac
-
 function find_file() {
     local description="$1"
     local sane_location="$2"
@@ -53,11 +30,49 @@ function find_file() {
     echo "${result}"
 }
 
-clang_index_h=$(find_file "libclang headers" "/usr/include/clang-c/Index.h" "/usr" "*/clang-c/Index.h")
-clang_include=$(dirname $(dirname ${clang_index_h}))
+printf "Looking for c++ compiler... "
+for x in clang++ g++; do
+    if which $x &>/dev/null; then
+        cxx=$x
+        break
+    fi
+done
+if [ -z "$cxx" ]; then
+    err "Cannot locate c++ compiler."
+fi
+printf "OK: ${cxx}\n"
 
-libclang_so=$(find_file "libclang library" "/usr/lib/libclang.so" "/usr" "*/libclang.so")
-clang_lib=$(dirname ${libclang_so})
+case $(uname) in
+    Darwin)
+        cxxflags="-std=c++11 -g -Wall"
+        ldflags="-lpthread"
+	if ! [ -e dev/ext/include/clang-c ]; then
+	    (
+		echo "Downloading clang headers..."
+		set -e
+		mkdir -p dev/ext/include
+		cd dev/ext/include
+		svn export http://llvm.org/svn/llvm-project/cfe/trunk/include/clang-c/
+		echo "Downloading clang headers...OK"
+	    )
+	else
+	    echo "Found clang headers."
+	fi
+	clang_include=-I"$PWD/dev/ext/include"
+	clang_lib_dir="`xcode-select --print-path`/Toolchains/XcodeDefault.xctoolchain/usr/lib"
+	clang_lib="-rpath ${clang_lib_dir} -L${clang_lib_dir} -lclang"
+        ;;        
+    *)
+        cxxflags="-std=c++11 -g -Wall"
+        ldflags="-lrt -lpthread"
+	clang_index_h=$(find_file "libclang headers" "/usr/include/clang-c/Index.h" "/usr" "*/clang-c/Index.h")
+	clang_include=-I$(dirname $(dirname ${clang_index_h}))
+
+	libclang_so=$(find_file "libclang library" "/usr/lib/libclang.so" "/usr" "*/libclang.so")
+	clang_lib="-L$(dirname ${libclang_so}) -lclang"
+        ;;
+esac
+
 
 printf "generating Makefile.conf..."
 sed -e "s|__configure_cxx__|$cxx|" \
