fix typos, minor refactor

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,40 +4,53 @@ set -e
 
 function err() {
     echo
-    echo "$@" 2>&1
+    echo "$@" 1>&2
     exit 1
 }
 
 printf "Looking for c++ compiler... "
-cxx=$(which clang++ 2>/dev/null)
-if [ -z "$cxx" ]; then
-    cxx=$(which g++ 2>/dev/null)
-fi
+for x in clang++ g++; do
+    if which $x &>/dev/null; then
+        cxx=$x
+        break
+    fi
+done
 if [ -z "$cxx" ]; then
     err "Cannot locate c++ compiler."
 fi
-echo "OK: $cxx"
+printf "OK: ${cxx}\n"
 
-search__clang_index_h='*/clang-c/Index.h'
-printf "Searching for ${search__clang_index_h=}... "
-clang_index_h=$(find /usr -path "${search__clang_index_h=}" | tail -1)
-if [ -z "$clang_index_h" ]; then
-    err "Cannot locate libclang headers -- looking for ${search__clang_index_h}"
-fi
+function find_file() {
+    local description="$1"
+    local sane_location="$2"
+    local find_root="$3"
+    local find_path="$4"
+    local result=""
+
+    printf "Searching for ${description}... " > /dev/tty
+    if [ -f "${sane_location}" ]; then
+        result="${sane_location}"
+    else
+        result=$(find "${find_root}" -path "${find_path}" | tail -1)
+    fi
+
+    if [ -z "${result}" ]; then
+        err "Cannot locate ${find_path}"
+    fi
+    printf "OK: ${result}\n" > /dev/tty
+    
+    echo "${result}"
+}
+
+clang_index_h=$(find_file "libclang headers" "/usr/include/clang-c/Index.h" "/usr" "*/clang-c/Index.h")
 clang_include=$(dirname $(dirname ${clang_index_h}))
-echo "OK: $clang_include"
 
-search__libclang_so='*/libclang.so'
-printf "Searching for ${search__libclang_so=}... "
-libclang_so=$(find /usr -path "${search__libclang_so=}" | tail -1)
-if [ -z "$libclang_so" ]; then
-    err "Cannot locate libclang headers -- looking for ${search__libclang_so}"
-fi
+libclang_so=$(find_file "libclang library" "/usr/lib/libclang.so" "/usr" "*/libclang.so")
 clang_lib=$(dirname ${libclang_so})
-echo "OK: $clang_lib"
 
-echo "generating Makefile.conf..."
+printf "generating Makefile.conf..."
 sed -e "s|__configure_cxx__|$cxx|" \
     -e "s|__configure_clang_include__|$clang_include|" \
     -e "s|__configure_clang_lib__|$clang_lib|" \
     Makefile.conf.in > Makefile.conf
+printf "OK\n"
